### PR TITLE
add TagView click event handle support

### PR DESCRIPTION
**Pull request by donly**
add onTap block to TagView

### CODE REVIEW

**Comment by pulimento** [comment]
Thanks, donly! Much appreciated :+1:

**Comment by donly** [comment]
Could you please update the pod, so I could use it directly, Thanks

**Comment by pulimento** [comment]
2015-11-11 2:17 GMT+01:00 Donly Chan notifications@github.com:

> the pod, so I could use it directly, Thanks

OK, I'm on it!

**Comment by pulimento** [comment]
Done!

**Pull request merged**
